//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int idPerson { get; set; }
        public string namePerson { get; set; }
        public string fNamePerson { get; set; }
        public string sNamePerson { get; set; }
        public System.DateTime dob { get; set; }
        public int idGender { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string photoPath { get; set; }
    
        public virtual Gender Gender { get; set; }
    }
}
